### ISSUE TITLE
How to encrypt iv for fixtures

### ISSUE THREAD

**Issue by volkerholloh** [attr-encrypted/attr_encrypted#261]
Hi there,

firstly, I want to thank everyone on working on this gem!

Can anyone tell me how to encrypt the iv value, so my fixtures are working?

I integrated the gem with the standard settings. My user model has a second password, called "safeword". The password itself is encrypted with "has_secure_password".

Now I want to protect the safeword, too, and if successful I would like to protect some other properties.

```
My user.rb

  attr_encrypted :safeword,
                 key: Rails.application.secrets.attr_encrypted_key,
                 encode: true,
                 encode_iv: true

```

My user.yml fixture
```
archer:
  name: SterlingArcher
  email: archer@example.com
  password_digest: <%= User.digest('password') %>
  encrypted_safeword: <%= User.encrypt_safeword('safeword', key: Rails.application.secrets.attr_encrypted_key, iv: 'aaaaaaaaaaaaaaaaaaaaaaaa') %>
  encrypted_safeword_iv: \xD0_P\x89(\x17\xF2\x1C\xD8y\xD5Q
  telephone_number: +111111111
```

After a lot of hours, that's how far I came. Without the :iv option, I get a "iv missing" error. 

Now I get an OpenSSL::Cipher::CipherError. I understand why I received it. The parameters od the decrypted safeword do not match those which are expected. At least, that's my assumption. :)

I could not figure out how to set the fixture up correctly. My guess is, that I have to calculate the encrypted_safeword_iv from the iv value. But how?

Any help is appreciated.

Thanks again!

Volker
