### ISSUE TITLE
attr_encrypted not working with in-memory sqlite database.

### ISSUE THREAD

**Issue by KurtPreston** [attr-encrypted/attr_encrypted#84]
When I attempt to save attr_encrypted fields while running the Rails database in memory, attr_encrypted fields do not seem to save properly.

To reproduce, change `config/database.yml` to the following:

```
test:
  adapter: sqlite3
  database: ":memory:"
  pool: 5
  timeout: 5000
```

All attr_encrypted fields will seem to save fine, but when you reload the record, the attr_encrypted fields will be `nil`.

These same tests will pass with a standard on-disk database, such as:

```
test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
```
